version: '3.8'

services:  
  redis:
    image: redis:7.4.0-alpine
    container_name: redis_for_websocket
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: madefire/chordtest
    command: ['celery', '-A', 'test_radio_websocket', 'worker', '-l', 'info']
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./:/app/
    depends_on:
      - redis

volumes:
  redis_data:
